# Generated by Django 4.2.10 on 2024-05-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='price',
        ),
        migrations.AlterField(
            model_name='detials',
            name='age',
            field=models.IntegerField(),
        ),
    ]
