# Generated by Django 4.2.10 on 2024-05-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product',
            new_name='category',
        ),
    ]
